spring.application.name=backend

# Configurações de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/neocondo
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Exibir os comandos SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true